server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop